---
version: "3"
services:
  homer:
    image: b4bz/homer:latest
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - D:/project/home/assets/:/www/assets
    ports:
      - 8082:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default