version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: always
    privileged: true
    user: root
    ports:
      - 8086:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - D:/project/jenkins/:/var/jenkins_home
